=== dimitrmo/cygaz-ai/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "CyGaz",
    "type": "object",
    "properties": {
        "updated_at": {
            "description": "Last updated time in milliseconds",
            "type": "integer",
            "examples": [
                1723729592807
            ]
        },
        "updated_at_str": {
            "description": "Last updated time in readable format",
            "type": "string",
            "examples": [
                "2024-08-15 13:46:32.000 UTC"
            ]
        },
        "petroleum_type": {
            "description": "Type of petroleum",
            "type": "string",
            "enum": [
                "Unlead95",
                "Unlead98",
                "DieselHeat",
                "DieselAuto",
                "Kerosene"
            ]
        },
        "stations": {
            "description": "List of stations",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "brand": {
                        "type": "string",
                        "examples": [
                            "BP"
                        ]
                    },
                    "offline": {
                        "type": "boolean"
                    },
                    "company": {
                        "type": "string",
                        "examples": [
                            "Company LTD"
                        ]
                    },
                    "address": {
                        "type": "string",
                        "examples": [
                            "Broadway Street"
                        ]
                    },
                    "latitude": {
                        "type": "string",
                        "examples": [
                            "40.730610"
                        ]
                    },
                    "longitude": {
                        "type": "string",
                        "examples": [
                            "-73.935242"
                        ]
                    },
                    "area": {
                        "type": "string",
                        "examples": [
                            "Soho"
                        ]
                    },
                    "price": {
                        "type": "number",
                        "examples": [
                            1.489
                        ]
                    }
                }
            },
            "additionalItems": false
        }
    }
}

=== dimitrmo/cygaz-ai/sample.json
{
    "updated_at": 1723729592807,
    "updated_at_str": "2024-08-15 13:46:32.000 UTC",
    "petroleum_type": "Unlead95",
    "stations": [
        {
            "brand": "ESSO",
            "offline": false,
            "company": "I.G. MAKRIS ENTERPRISES LTD",
            "address": "Καντάρας 58 Τ.Κ 1037\n τηλ: 22433430",
            "latitude": "35.1845138888889",
            "longitude": "33.3895",
            "area": "Καϊμακλί",
            "price": 1.449
        },
        {
            "brand": "PETROLINA",
            "offline": false,
            "company": "MICHALIS KNEKNAS TRADING LTD",
            "address": "Γρηγόρη Αυξεντίου 76, Κοκκινοτριμιθιά Τ.Κ 2660\n τηλ: 22834160",
            "latitude": "35.148666",
            "longitude": "33.212235",
            "area": "Κοκκινοτριμιθιά",
            "price": 1.489
        },
        {
            "brand": "ESSO",
            "offline": true,
            "company": "\"ΑΔΕΛΦΟΙ ΚΟΥΡΙΔΗ ΛΙΜΙΤΕΔ\"",
            "address": "Ευαγόρα Παλληκαρίδη 53 Τ.Κ 8010\n τηλ: 26933657",
            "latitude": "34.7779977652251",
            "longitude": "32.4236665755325",
            "area": "Πάφος",
            "price": 1.49
        },
        {
            "brand": "ESSO",
            "offline": false,
            "company": "A &amp; K PAVLOU TRADING LIMITED",
            "address": "Πάφου 21 Τ.Κ 3052\n τηλ: 25562279",
            "latitude": "34.6744035108073",
            "longitude": "33.013875861377",
            "area": "Λεμεσός",
            "price": 1.485
        },
        {
            "brand": "EKO",
            "offline": false,
            "company": "A G A PETROL STATION LIMITED",
            "address": "Λεωφ. Λουκή Ακρίτα 1 Τ.Κ 1100\n τηλ: 22774819",
            "latitude": "35.17265",
            "longitude": "33.350405",
            "area": "Λευκωσία",
            "price": 1.499
        },
        {
            "brand": "PETROLINA",
            "offline": false,
            "company": "A. K. Konnaris Service Station Ltd",
            "address": "Παναγίας Ελεούσας 55 Τ.Κ 4730\n τηλ: 25432020",
            "latitude": "34.8458",
            "longitude": "32.9121",
            "area": "Τριμίκλινη",
            "price": 1.515
        },
        {
            "brand": "PETROLINA",
            "offline": false,
            "company": "A. K. Konnaris Service Station Ltd (Platres)",
            "address": "Παναγίας Φανερωμένης 57 Τ.Κ\n τηλ: 25421100",
            "latitude": "34.8843",
            "longitude": "32.8633",
            "area": "Πάνω Πλάτρες",
            "price": 1.538
        },
        {
            "brand": "PETROLINA",
            "offline": false,
            "company": "A.C.C. AVRAAM ENTERPRISES LIMITED",
            "address": "Λεωφ. Λουκή Ακρίτα 15 Τ.Κ 1100\n τηλ: 22771700",
            "latitude": "35.17211667",
            "longitude": "33.34798333",
            "area": "Λευκωσία",
            "price": 1.495
        },
        {
            "brand": "EKO",
            "offline": false,
            "company": "A.L. SERVICE STATION LIMITED",
            "address": "Γ. Κρανιδιώτη 5 Τ.Κ 2220\n τηλ: 22489888",
            "latitude": "35.116846",
            "longitude": "33.377618",
            "area": "Λατσιά",
            "price": 1.558
        },
        {
            "brand": "ESSO",
            "offline": false,
            "company": "A.V. FUELS LIMITED",
            "address": "Μισιαούλη &amp; Καβάζογλου 86-88 Τ.Κ 3016\n τηλ: 25565274",
            "latitude": "34.673999828282",
            "longitude": "33.0231830443581",
            "area": "Λεμεσός",
            "price": 1.456
        },
        {
            "brand": "EKO",
            "offline": false,
            "company": "ANDREAS THEOCHAROUS (PETROL STATION) LIMITED",
            "address": "Λεωφ.Αρχ. Μακαρίου Γ' 70, Αστρομερίτης  Τ.Κ 2722\n τηλ: 22821312",
            "latitude": "35.138374",
            "longitude": "33.051492",
            "area": "Αστρομερίτης",
            "price": 1.491
        },
        {
            "brand": "ESSO",
            "offline": true,
            "company": "ANGIO TRADING LIMITED",
            "address": "Λεωφ. Νίκης 37 Τ.Κ 1087\n τηλ: 22490810",
            "latitude": "35.1565679511699",
            "longitude": "33.3580602362457",
            "area": "Ακρόπολη",
            "price": 1.477
        },
        {
            "brand": "ESSO",
            "offline": false,
            "company": "ANMAS LTD",
            "address": "Λεωφ. Γρηγόρη Αυξεντίου 154 Τ.Κ 2365\n τηλ: 22771034",
            "latitude": "35.1723546547892",
            "longitude": "33.3232578673897",
            "area": "Άγιος Δομέτιος",
            "price": 1.509
        }
    ]
}
